### ISSUE TITLE
Logo offer for Remoter

### ISSUE THREAD

**Issue by familqasimov** [ogasimli/Remoter#1]
Hi sir Orkhan. I'm graphic designer. I would like to offer logo. If you like, I can give you with great pleasure all the formats of the design free. If you want a change please specify.

![untitled-2](https://user-images.githubusercontent.com/36432269/42741733-e542883a-88c5-11e8-8665-10574985c635.png)

Best regard
Famil Gasimov

**Comment by ogasimli** [comment]
Hi Famil,

Thank you very much for this beautiful logo design. It is very nice from you. I would be more than happy to receive the design files of the logo. Please feel free to share them with here as PR or send me through my email address.

However please note, that the project is currently in early development stage. Currently, I haven't made any final decisions about design aspects of the project. Therefore the logo proposed by you may be subject to changes. If you are ok with that, I can ask you to make some changes to the logo as soon as I will decide about the main aspects of app's design.
